
package com.yusei.service.impl;

import java.util.List;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;


import com.yusei.service.IFieldExtendRuleService;
import com.yusei.dao.FieldExtendRuleDao;
import com.yusei.model.entity.FieldExtendRule;
import org.springframework.util.CollectionUtils;

/**
 * 扩展规则表Service实现
 *
 * @author generated by liuqiang
 * @date 2020-09-02 13:58:06
 */
@Service
public class IFieldExtendRuleServiceImpl implements IFieldExtendRuleService {

    @Autowired
    private FieldExtendRuleDao fieldExtendRuleDao;

    /**
     * 根据条件查询FieldExtendRule list
     */
    @Override
    public List<FieldExtendRule> selectByRecord(FieldExtendRule record) {
        return fieldExtendRuleDao.selectByRecord(record);
    }

    @Override
    public int insertBatch(List<FieldExtendRule> fieldExtendRuleList) {
        if (!CollectionUtils.isEmpty(fieldExtendRuleList)) {
            return fieldExtendRuleDao.insertBatch(fieldExtendRuleList);
        }

        return 0;
    }

    @Override
    public List<FieldExtendRule> selectByFieldIdList(List<Long> fieldIdList) {
        return fieldExtendRuleDao.selectByFieldIdList(fieldIdList);
    }

    @Override
    public int deleteByExtendRuleIdList(List<Long> ruleIdList) {
        if ( CollectionUtils.isEmpty(ruleIdList)){
            return 0;
        }
        return fieldExtendRuleDao.deleteByExtendRuleIdList(ruleIdList);
    }
}
