
package com.yusei.service;

import java.util.List;
import java.util.Map;


import com.yusei.model.entity.FieldExtendRuleDetail;

/**
 * 扩展规则详情表Service
 *
 * @author generated by liuqiang
 * @date 2020-09-02 13:58:18
 */
public interface IFieldExtendRuleDetailService {

    void insertBatch(List<FieldExtendRuleDetail> fieldExtendRuleDetailList);

    Map<Long, List<FieldExtendRuleDetail>> selectMapByRuleIdList(List<Long> extendRuleIdList);

    int deleteByExtendRuleIdList(List<Long> ruleIdList);
}
