
package com.yusei.service;

import java.util.List;


import com.yusei.model.entity.FieldExtendRule;

/**
 * 扩展规则表Service
 *
 * @author generated by liuqiang
 * @date 2020-09-02 13:58:06
 */
public interface IFieldExtendRuleService {

    /**
     * 根据条件查询FieldExtendRule list
     */
    List<FieldExtendRule> selectByRecord(FieldExtendRule record);


    int insertBatch(List<FieldExtendRule> fieldExtendRuleList);

    List<FieldExtendRule> selectByFieldIdList(List<Long> fieldIdList);

    int deleteByExtendRuleIdList(List<Long> ruleIdList);
}
