
package com.yusei.dao;

import java.util.List;
import java.util.Date;
import java.math.BigDecimal;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


import com.yusei.model.entity.FieldExtendData;

/**
 * FieldExtendDataDao
 * @author generated by liuqiang
 * @date 2020-08-31 16:42:39
 */
@Mapper
public interface FieldExtendDataDao {

  /**
   * 根据条件查询FieldExtendData列表, record封装查询条件（都是=）
   */
  List<FieldExtendData> selectByRecord(FieldExtendData record);

  /**
   * 批量插入记录，返回插入成功的行数(不插入主键)
   */
  int insertBatch(@Param("list") List<FieldExtendData> list);

    int deleteByFieldIdList(@Param("list") List<Long> fieldIdList);
}
