
package com.yusei.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


import com.yusei.model.entity.FieldExtendRuleDetail;

/**
 * 扩展规则详情表Dao
 *
 * @author generated by liuqiang
 * @date 2020-09-02 13:58:18
 */
@Mapper
public interface FieldExtendRuleDetailDao {
    /**
     * 批量插入记录，返回插入成功的行数(不插入主键)
     */
    int insertBatch(@Param("list") List<FieldExtendRuleDetail> list);

    List<FieldExtendRuleDetail> selectListByRuleIdList(@Param("list") List<Long> extendRuleIdList);

    int deleteByExtendRuleIdList(@Param("list") List<Long> ruleIdList);
}
