
package com.yusei.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


import com.yusei.model.entity.FieldExtendRule;

/**
 * 扩展规则表Dao
 *
 * @author generated by liuqiang
 * @date 2020-09-02 13:58:06
 */
@Mapper
public interface FieldExtendRuleDao {

    /**
     * 根据条件查询FieldExtendRule列表, record封装查询条件（都是=）
     */
    List<FieldExtendRule> selectByRecord(FieldExtendRule record);

    /**
     * 批量插入记录，返回插入成功的行数(不插入主键)
     */
    int insertBatch(@Param("list") List<FieldExtendRule> list);

    List<FieldExtendRule> selectByFieldIdList(@Param("list") List<Long> fieldIdList);

    int deleteByExtendRuleIdList(@Param("list")List<Long> ruleIdList);
}
