package com.yusei.model.entity;

import java.util.Date;
import java.math.BigDecimal;
import java.io.Serializable;

import lombok.Data;
import lombok.experimental.Accessors;

/**
 * 扩展规则表实体类
 * @author generated by liuqiang
 * @date 2020-09-02 13:58:06
 */
@Data
@Accessors(chain = true)
public class FieldExtendRule implements Serializable {

  /**
   * 
   */
  private Long fieldExtendRuleId;
  /**
   * 
   */
  private Long formId;
  /**
   * 
   */
  private Long fieldId;
  /**
   * 
   */
  private String type;
  /**
   * 
   */
  private String name;
}