package com.yusei.model.entity;

import java.util.Date;
import java.math.BigDecimal;
import java.io.Serializable;

import lombok.Data;
import lombok.experimental.Accessors;

/**
 * 扩展规则详情表实体类
 * @author generated by liuqiang
 * @date 2020-09-02 13:58:18
 */
@Data
@Accessors(chain = true)
public class FieldExtendRuleDetail implements Serializable {

  /**
   * 主键id
   */
  private Long fieldExtendRuleDetailId;
  /**
   * 
   */
  private Long fieldExtendRuleId;
  /**
   * 
   */
  private String rule;
  /**
   * 
   */
  private String value;
}